<!--#include virtual=/sb/inc/vbutil.inc-->
<%
noti_id=0	
sql="ANG_USP_NOTI_INFO_SAVE "
sql=sql&" "&noti_id&" ,"
sql=sql&" '"&title&"' ,"  
sql=sql&" '"&title_eng&"' ,"  
sql=sql&" '"&title_chn&"' ,"  
sql=sql&" '"&title_jpn&"' ,"  
sql=sql&" '"&sub_title&"' ,"  
sql=sql&" '"&sub_title_eng&"' ,"  
sql=sql&" '"&sub_title_chn&"' ,"  
sql=sql&" '"&sub_title_jp&"' ,"  
sql=sql&" '"&mail_body&"' ,"  
sql=sql&" '"&mail_body_eng&"' ,"  
sql=sql&" '"&mail_body_chn&"' ,"  
sql=sql&" '"&mail_body_jpn&"' ,"  
sql=sql&" '"&lms_body&"' ,"  
sql=sql&" '"&kakao_body&"' ,"  
sql=sql&" '"&due_date&"' ,"  
sql=sql&" '"&due&"' ,"  
sql=sql&" '"&mail_flag&"' ,"  
sql=sql&" '"&lms_flag&"' ,"  
sql=sql&" '"&fcm_flag&"' ,"  
sql=sql&" '"&kakao_flag&"' ,"  
sql=sql&" '"&sent_date&"' ,"  
sql=sql&" '"&results&"' ,"  
sql=sql&" '"&exeOption&"' ,"  
sql=sql&" '"&admin_id&"' "  
response.write sql	
%>